.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. patentcoin_qt test_patentcoin_qt
clean: FORCE
	$(MAKE) -C .. patentcoin_qt_clean test_patentcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_patentcoin_qt_check
patentcoin-qt patentcoin-qt.exe: FORCE
	 $(MAKE) -C .. patentcoin_qt
